name: branch-build
on:
    push:
        branches: 
            - '*'
            - '!master'
jobs:
    build-workflow:
      name: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Setup Go
          uses: actions/setup-go@v5
          with:
            go-version: '>=1.23.0'
        - name: Install dependencies
          run: |
              go version
              go get
        - name: test
          run: |
            go test -v ./...
        - name: build
          run: |
            go build . 
