name: build
on:
    push:
        branches: 
            - '*'
            - '!master'
    pull_request:
        branches:
            - '*'
jobs:
    setup-workflow:
      name: setup
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: setup go
          uses: actions/setup-go@v5
          with:
            go-version: '>=1.23.0'
        - name: Install dependencies
          run: |
              go version
              go get
        - name: test
          run: |
            go test -v ./...
    build-workflow:
        name: build
        needs: setup-workflow
        runs-on: ubuntu-latest
        strategy:
            matrix:
                goos:
                    - linux
                goarch:
                    - amd64
                    - arm64
                flags:
                    - -trimpath
        steps:
            - uses: actions/checkout@v4
            - name: setup go
              uses: actions/setup-go@v5
              with:
                go-version: '>=1.23.0'
            - name: build
              env:
                GOOS: ${{ matrix.goos }}
                GOARCH: ${{ matrix.goarch }}
                CGO_ENABLED: 0
              run: |
                go build -mod vendor ${{ matrix.flags }}  . 
    release-workflow:
        name: release
        needs: build-workflow
        runs-on: ubuntu-latest
        if: ${{ github.ref_name == 'master' }}
        steps:
            - name: release
              run: |
                echo release
    